package com.example.neglectapp.core

object Constants {
    const val ACTION_SERVICE_START = "ACTION_SERVICE_START"
    const val ACTION_SERVICE_STOP = "ACTION_SERVICE_STOP"
    const val ACTION_SERVICE_CANCEL = "ACTION_SERVICE_CANCEL"
    const val ACTION_TRIGGER_ALARM = "ACTION_TRIGGER_ALARM"
    const val ACTION_SHOW_ALARM = "ACTION_SHOW_ALARM"
    const val SESSION_STATE = "SESSION_STATE"

    const val NOTIFICATION_CHANNEL_ID = "SESSION_NOTIFICATION_ID"
    const val NOTIFICATION_CHANNEL_NAME = "SESSION_NOTIFICATION"
    const val NOTIFICATION_ID = 10

    const val CLICK_REQUEST_CODE = 100
    const val CANCEL_REQUEST_CODE = 101
    const val STOP_REQUEST_CODE = 102
    const val RESUME_REQUEST_CODE = 103

    const val SESSION_TABLE = "session_table"
}